services:
  server:
    build:
      context: ..
    env_file:
      - ../.env.docker
    ports:
      - 3672:3672
  
#docker compose -f .docker/development-docker-compose.yaml -p claw-machine-backend up --build -d 