services:
  server:
    build:
      context: ..
    environment:
      POSTGRES_MASTER_HOST: ${POSTGRES_MASTER_HOST}
      POSTGRES_MASTER_PORT: ${POSTGRES_MASTER_PORT}
      POSTGRES_MASTER_USERNAME: ${POSTGRES_MASTER_USERNAME}
      POSTGRES_MASTER_PASSWORD: ${POSTGRES_MASTER_PASSWORD}
      POSTGRES_MASTER_DATABASE: ${POSTGRES_MASTER_DATABASE}
      POSTGRES_MASTER_MOCK_DATABASE: ${POSTGRES_MASTER_MOCK_DATABASE}

      POSTGRES_SLAVE_1_HOST: ${POSTGRES_SLAVE_1_HOST}
      POSTGRES_SLAVE_1_PORT: ${POSTGRES_SLAVE_1_PORT}
      POSTGRES_SLAVE_1_USERNAME: ${POSTGRES_SLAVE_1_USERNAME}
      POSTGRES_SLAVE_1_PASSWORD: ${POSTGRES_SLAVE_1_PASSWORD}
      POSTGRES_SLAVE_1_DATABASE: ${POSTGRES_SLAVE_1_DATABASE}
      POSTGRES_SLAVE_1_MOCK_DATABASE: ${POSTGRES_SLAVE_1_MOCK_DATABASE}
        
      PORT: ${PORT}
      NODE_ENV: ${NODE_ENV}

      SSL_CERT: ${SSL_CERT}
      SSL_KEY: ${SSL_KEY}
    ports:
      - 3672:3672
